// data.js - TÜM OYUN VERİSİNİ TUTAN DOSYA

const gameData = {
  "kelimeler": [
    {"ar": "أَنَا", "tr": "Ben", "tip": "ZAMİR", "seviye": 1},
    {"ar": "هُوَ", "tr": "O (erkek)", "tip": "ZAMİR", "seviye": 1},
    {"ar": "هِيَ", "tr": "O (kadın)", "tip": "ZAMİR", "seviye": 1},
    {"ar": "كِتَاب", "tr": "Kitap", "tip": "İSİM", "seviye": 2},
    {"ar": "مَدْرَسَة", "tr": "Okul", "tip": "İSİM", "seviye": 2},
    {"ar": "سَيَّارَة", "tr": "Araba", "tip": "İSİM", "seviye": 2},
    {"ar": "ذَهَبَ", "tr": "Gitti", "tip": "FİİL", "sevi": 3},
    {"ar": "أَكَلَ", "tr": "Yedi", "tip": "FİİL", "sevi": 3},
    {"ar": "شَرِبَ", "tr": "İçti", "tip": "FİİL", "sevi": 3},
    {"ar": "كَبِير", "tr": "Büyük", "tip": "SIFAT", "sevi": 4},
    {"ar": "صَغِير", "tr": "Küçük", "tip": "SIFAT", "sevi": 4},
    {"ar": "جَمِيل", "tr": "Güzel", "tip": "SIFAT", "sevi": 4},
    {"ar": "الْآن", "tr": "Şimdi", "tip": "ZARF", "seviye": 5},
    {"ar": "أَمْس", "tr": "Dün", "tip": "ZARF", "seviye": 5},
    {"ar": "فِي", "tr": "İçinde", "tip": "EDAT", "seviye": 5},
    {"ar": "أَنْتَ", "tr": "Sen (erkek)", "tip": "ZAMİR", "seviye": 1},
    {"ar": "أَنْتِ", "tr": "Sen (kadın)", "tip": "ZAMİR", "seviye": 1},
    {"ar": "نَحْنُ", "tr": "Biz", "tip": "ZAMİR", "seviye": 1},
    {"ar": "مَاذَا", "tr": "Ne", "tip": "SORU", "seviye": 1},
    {"ar": "كَيْفَ", "tr": "Nasıl", "tip": "SORU", "seviye": 1},
    {"ar": "مَنْ", "tr": "Kim", "tip": "SORU", "seviye": 2},
    {"ar": "أَيْنَ", "tr": "Nerede", "tip": "SORU", "seviye": 2},
    {"ar": "مَتَى", "tr": "Ne zaman", "tip": "SORU", "seviye": 2},
    {"ar": "قَلَم", "tr": "Kalem", "tip": "İSİM", "seviye": 2},
    {"ar": "بَيْت", "tr": "Ev", "tip": "İSİM", "seviye": 2},
    {"ar": "طَعَام", "tr": "Yemek", "tip": "İSİM", "seviye": 2},
    {"ar": "مَاء", "tr": "Su", "tip": "İSİM", "seviye": 3},
    {"ar": "شَارِع", "tr": "Cadde", "tip": "İSİM", "seviye": 3},
    {"ar": "طَبِيب", "tr": "Doktor", "tip": "İSİM", "seviye": 3},
    {"ar": "مُعَلِّم", "tr": "Öğretmen", "tip": "İSİM", "seviye": 3},
    {"ar": "قَرَأَ", "tr": "Okudu", "tip": "FİİL", "seviye": 3},
    {"ar": "كَتَبَ", "tr": "Yazdı", "tip": "FİİL", "seviye": 3},
    {"ar": "نَظَرَ", "tr": "Baktı", "tip": "FİİL", "seviye": 4},
    {"ar": "جَلَسَ", "tr": "Oturdu", "tip": "FİİL", "seviye": 4},
    {"ar": "فَتَحَ", "tr": "Açtı", "tip": "FİİL", "seviye": 4},
    {"ar": "أَغْلَقَ", "tr": "Kapattı", "tip": "FİİL", "seviye": 4},
    {"ar": "جَدِيد", "tr": "Yeni", "tip": "SIFAT", "seviye": 5},
    {"ar": "قَدِيم", "tr": "Eski", "tip": "SIFAT", "seviye": 5},
    {"ar": "سَرِيع", "tr": "Hızlı", "tip": "SIFAT", "seviye": 5},
    {"ar": "بَطِيء", "tr": "Yavaş", "tip": "SIFAT", "seviye": 5},
    {"ar": "غَدًا", "tr": "Yarın", "tip": "ZARF", "seviye": 6},
    {"ar": "عَلَى", "tr": "Üzerinde", "tip": "EDAT", "seviye": 6},
    {"ar": "لِأَنَّ", "tr": "Çünkü", "tip": "BAĞLAÇ", "seviye": 6},
    {"ar": "وَ", "tr": "Ve", "tip": "BAĞLAÇ", "seviye": 6},
    {"ar": "أُسْبُوع", "tr": "Hafta", "tip": "İSİM", "seviye": 7},
    {"ar": "شَهْر", "tr": "Ay", "tip": "İSİM", "seviye": 7},
    {"ar": "عَائِلَة", "tr": "Aile", "tip": "İSİM", "seviye": 8},
    {"ar": "أَب", "tr": "Baba", "tip": "İSİM", "seviye": 8},
    {"ar": "أُم", "tr": "Anne", "tip": "İSİM", "seviye": 8},
    {"ar": "صَدِيق", "tr": "Arkadaş", "tip": "İSİM", "seviye": 10},
    {"ar": "حَزِين", "tr": "Üzgün", "tip": "SIFAT", "seviye": 11},
    {"ar": "سَعِيد", "tr": "Mutlu", "tip": "SIFAT", "seviye": 11},
    {"ar": "أَحْمَر", "tr": "Kırmızı", "tip": "SIFAT", "seviye": 18},
    {"ar": "أَزْرَق", "tr": "Mavi", "tip": "SIFAT", "seviye": 18},
    {"ar": "أَخْضَر", "tr": "Yeşil", "tip": "SIFAT", "seviye": 18},
    {"ar": "أَسْوَد", "tr": "Siyah", "tip": "SIFAT", "seviye": 18}
  ],
  "cumleler": [
    {"ar": "أَنَا طَالِبٌ فِي الْمَدْرَسَة", "tr": "Ben okulda bir öğrenciyim.", "seviye": 1},
    {"ar": "هَلْ تَسْكُنُ هُنَا؟", "tr": "Burada mı oturuyorsun?", "seviye": 1},
    {"ar": "أُرِيدُ قَهْوَة سَاخِنَة", "tr": "Sıcak bir kahve istiyorum.", "seviye": 1},
    {"ar": "مَاذَا تَفْعَلُ الْآن؟", "tr": "Şimdi ne yapıyorsun?", "seviye": 1},
    {"ar": "كَيْفَ حَالُكَ الْيَوْم؟", "tr": "Bugün nasılsın?", "seviye": 1},
    {"ar": "السَّيَّارَةُ جَدِيدَةٌ وَكَبِيرَة", "tr": "Araba yeni ve büyüktür.", "seviye": 2},
    {"ar": "نَحْنُ نَذْهَبُ إِلَى الْمَتْجَر", "tr": "Biz mağazaya gidiyoruz.", "seviye": 2},
    {"ar": "الطَّعَامُ لَذِيذٌ جِدًا", "tr": "Yemek çok lezzetli.", "seviye": 2},
    {"ar": "أَيْنَ كِتَابِي؟", "tr": "Kitabım nerede?", "seviye": 2},
    {"ar": "أَنَا أُحِبُّ عَمَلِي", "tr": "İşimi seviyorum.", "seviye": 3},
    {"ar": "هِيَ تَشْرَبُ الْمَاء", "tr": "O su içiyor.", "seviye": 3},
    {"ar": "أَخِي طَوِيل وَأَنَا قَصِير", "tr": "Erkek kardeşim uzun, ben ise kısayım.", "seviye": 3},
    {"ar": "هَلْ قَرَأْتَ هَذَا الْكِتَاب؟", "tr": "Bu kitabı okudun mu?", "seviye": 3},
    {"ar": "هَذَا الْبَيْتُ قَدِيم", "tr": "Bu ev eskidir.", "seviye": 3},
    {"ar": "سَنَذْهَبُ إِلَى الْمَطْعَم غَدًا", "tr": "Yarın restorana gideceğiz.", "seviye": 4},
    {"ar": "أَنَا سَعِيد بِرُؤْيَتِكَ", "tr": "Seni gördüğüme sevindim.", "seviye": 4},
    {"ar": "يُمْكِنُنِي مُسَاعَدَتُك", "tr": "Sana yardım edebilirim.", "seviye": 4},
    {"ar": "نَحْنُ نَنْتَظِرُ الْقِطَار", "tr": "Biz treni bekliyoruz.", "seviye": 5},
    {"ar": "هَلْ تَسْتَطِيعُ الْقِيَادَة؟", "tr": "Araba kullanabilir misin?", "seviye": 5},
    {"ar": "هَلْ هَذَا صَحِيح أَمْ خَطَأ؟", "tr": "Bu doğru mu yoksa yanlış mı?", "seviye": 5}
  ],
  "eksik_kelime_cumleleri": [
    {"ar": "أَنَا أَشْرَبُ الْقَهْوَةَ كُلَّ [يَوْم]", "tr": "Ben her [gün] kahve içerim.", "dogru": "يَوْم"},
    {"ar": "هِيَ تَذْهَبُ إِلَى [الْعَمَل] بِالْحَافِلَة", "tr": "O otobüsle [işe] gider.", "dogru": "الْعَمَل"},
    {"ar": "نَحْنُ نَأْكُلُ فِي [الْمَطْعَم]", "tr": "Biz [lokantada] yemek yeriz.", "dogru": "الْمَطْعَم"},
    {"ar": "أَيْنَ [الْمُعَلِّم] الْآن؟", "tr": "[Öğretmen] şimdi nerede?", "dogru": "الْمُعَلِّم"},
    {"ar": "هَذِهِ [سَيَّارَة] جَدِيدَة", "tr": "Bu yeni bir [arabadır].", "dogru": "سَيَّارَة"},
    {"ar": "أُرِيدُ أَنْ [أَجْلِس] مَعَكَ", "tr": "Seninle [oturmak] istiyorum.", "dogru": "أَجْلِس"},
    {"ar": "هُوَ [نَظَرَ] إِلَى السَّمَاء", "tr": "O gökyüzüne [baktı].", "dogru": "نَظَرَ"},
    {"ar": "مَتَى [سَتَذْهَبُ] إِلَى الْمَتْجَر؟", "tr": "[Mağazaya] ne zaman gideceksin?", "dogru": "سَتَذْهَبُ"}
  ]
};
